<?php

namespace Trig\SimpleShopBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Trig\SimpleShopBundle\Entity\Car;

class CarAudiA7 extends AbstractFixture implements OrderedFixtureInterface{
    
    public function load(ObjectManager $manager) {
        $car = new Car();
        $car->setName('Audi A7');
        $car->setPrice('75000');
        $car->setImage("/bundles/trigsimpleshop/img/audi/minimized/mnmz_http--go-go.com.ua-images-stories-00audi_sportback_concept_a7_1.jpg");
        $lDesc = <<< LDESC
   The A7 marked Audi's return to the executive hatchback market since the 1970 three-door Audi 100 Coupe of 1970 and the 1977 five-door 100 Avant. It was announced at the Pinakothek der Moderne art museum in Munich on 27 July 2010 and débuted at the 2010 Paris Motor Show. The car was launched in the US at the New York Auto Show in April 2011 as a 2012 model.
The A7 was preceded by a concept car, the Audi Sportback concept shown at the 2009 Detroit Auto Show. The concept car first spawned the Audi A5 Sportback which was released September 2009 as a 2010 model.
LDESC;
        $sDesc = <<< SDESC
  The Audi A7 Sportback (internally designated Typ 4G) is an executive car produced by Audi. It is a five-door fastback which is frequently described as a "four door coupé" with its sleek profile and frameless doors. The A7 is based on the Volkswagen Group MLB platform, which is shared with the upcoming fourth-generation (C7) 2012 Audi A6; with the coupé-like A7 being released before the conventional A6 saloon/wagon. 
SDESC;
        $urls = <<< URLS
<li id="cite_note-0"><span class="mw-cite-backlink"><b><a href="#cite_ref-0">^</a></b></span> <span class="reference-text"><span class="citation web">Friday, 30 July 2010 (30 July 2010). <a rel="nofollow" class="external text" href="http://www.autocar.co.uk/News/NewsArticle/AllCars/251571/">"30 July 2010"</a>. Autocar.co.uk<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.autocar.co.uk/News/NewsArticle/AllCars/251571/">http://www.autocar.co.uk/News/NewsArticle/AllCars/251571/</a></span><span class="reference-accessdate">. Retrieved 17 June 2011</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=30+July+2010&amp;rft.atitle=&amp;rft.aulast=Friday%2C+30+July+2010&amp;rft.au=Friday%2C+30+July+2010&amp;rft.date=30+July+2010&amp;rft.pub=Autocar.co.uk&amp;rft_id=http%3A%2F%2Fwww.autocar.co.uk%2FNews%2FNewsArticle%2FAllCars%2F251571%2F&amp;rfr_id=info:sid/en.wikipedia.org:Audi_A7"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-1"><span class="mw-cite-backlink"><b><a href="#cite_ref-1">^</a></b></span> <span class="reference-text"><span class="citation web">Knapman, Chris (28 January 2011). <a rel="nofollow" class="external text" href="http://www.telegraph.co.uk/motoring/car-manufacturers/audi/8287050/Audi-A6-review.html">"The Telegraph 28 January 2011"</a>. Telegraph.co.uk<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.telegraph.co.uk/motoring/car-manufacturers/audi/8287050/Audi-A6-review.html">http://www.telegraph.co.uk/motoring/car-manufacturers/audi/8287050/Audi-A6-review.html</a></span><span class="reference-accessdate">. Retrieved 17 June 2011</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=The+Telegraph+28+January+2011&amp;rft.atitle=&amp;rft.aulast=Knapman&amp;rft.aufirst=Chris&amp;rft.au=Knapman%2C%26%2332%3BChris&amp;rft.date=28+January+2011&amp;rft.pub=Telegraph.co.uk&amp;rft_id=http%3A%2F%2Fwww.telegraph.co.uk%2Fmotoring%2Fcar-manufacturers%2Faudi%2F8287050%2FAudi-A6-review.html&amp;rfr_id=info:sid/en.wikipedia.org:Audi_A7"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-2"><span class="mw-cite-backlink"><b><a href="#cite_ref-2">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://wot.motortrend.com/2011-new-york-audi-a7-available-2011-starts-59250-69633.html">"2011 New York: Audi A7 Available in the U.S. in May 2011, Starts at $59,250"</a>. <i>Motor Trend</i><span class="printonly">. <a rel="nofollow" class="external free" href="http://wot.motortrend.com/2011-new-york-audi-a7-available-2011-starts-59250-69633.html">http://wot.motortrend.com/2011-new-york-audi-a7-available-2011-starts-59250-69633.html</a></span><span class="reference-accessdate">. Retrieved 1 June 2011</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=2011+New+York%3A+Audi+A7+Available+in+the+U.S.+in+May+2011%2C+Starts+at+%2459%2C250&amp;rft.atitle=Motor+Trend&amp;rft_id=http%3A%2F%2Fwot.motortrend.com%2F2011-new-york-audi-a7-available-2011-starts-59250-69633.html&amp;rfr_id=info:sid/en.wikipedia.org:Audi_A7"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-car-3"><span class="mw-cite-backlink"><b><a href="#cite_ref-car_3-0">^</a></b></span> <span class="reference-text"><span class="citation web">Pollard, Tim (12 January 2009). <a rel="nofollow" class="external text" href="http://www.carmagazine.co.uk/News/Search-Results/Motor-show--events/Detroit-Motor-Show-/2009/Audi-Sportback-unveiled-at-Detroit-auto-show-2009-110109/">"Audi Sportback unveiled at Detroit auto show 2009"</a>. <i><a href="/wiki/Car_Magazine" title="Car Magazine">Car Magazine</a></i><span class="printonly">. <a rel="nofollow" class="external free" href="http://www.carmagazine.co.uk/News/Search-Results/Motor-show--events/Detroit-Motor-Show-/2009/Audi-Sportback-unveiled-at-Detroit-auto-show-2009-110109/">http://www.carmagazine.co.uk/News/Search-Results/Motor-show--events/Detroit-Motor-Show-/2009/Audi-Sportback-unveiled-at-Detroit-auto-show-2009-110109/</a></span><span class="reference-accessdate">. Retrieved 19 January 2009</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=Audi+Sportback+unveiled+at+Detroit+auto+show+2009&amp;rft.atitle=%5B%5BCar+Magazine%5D%5D&amp;rft.aulast=Pollard&amp;rft.aufirst=Tim&amp;rft.au=Pollard%2C%26%2332%3BTim&amp;rft.date=12+January+2009&amp;rft_id=http%3A%2F%2Fwww.carmagazine.co.uk%2FNews%2FSearch-Results%2FMotor-show--events%2FDetroit-Motor-Show-%2F2009%2FAudi-Sportback-unveiled-at-Detroit-auto-show-2009-110109%2F&amp;rfr_id=info:sid/en.wikipedia.org:Audi_A7"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-autocar-20100726-4"><span class="mw-cite-backlink"><b><a href="#cite_ref-autocar-20100726_4-0">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.autocar.co.uk/News/NewsArticle/AllCars/251571/">"Audi A7 revealed"</a>. <i><a href="/wiki/Autocar" title="Autocar">Autocar</a></i>. 26 July 2010. <a rel="nofollow" class="external text" href="http://web.archive.org/web/20100728055242/http://www.autocar.co.uk/News/NewsArticle/AllCars/251571/">Archived</a> from the original on 28 July 2010<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.autocar.co.uk/News/NewsArticle/AllCars/251571/">http://www.autocar.co.uk/News/NewsArticle/AllCars/251571/</a></span><span class="reference-accessdate">. Retrieved 28 July 2010</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=Audi+A7+revealed&amp;rft.atitle=%5B%5BAutocar%5D%5D&amp;rft.date=26+July+2010&amp;rft_id=http%3A%2F%2Fwww.autocar.co.uk%2FNews%2FNewsArticle%2FAllCars%2F251571%2F&amp;rfr_id=info:sid/en.wikipedia.org:Audi_A7"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-audiusa-20110227-5"><span class="mw-cite-backlink"><b><a href="#cite_ref-audiusa-20110227_5-0">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://brochures.audiusa.com/brochures/audi.a7.2012/index.html">"Audi USA A7 brochure"</a><span class="printonly">. <a rel="nofollow" class="external free" href="http://brochures.audiusa.com/brochures/audi.a7.2012/index.html">http://brochures.audiusa.com/brochures/audi.a7.2012/index.html</a></span><span class="reference-accessdate">. Retrieved 27 February 2012</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=Audi+USA+A7+brochure&amp;rft.atitle=&amp;rft_id=http%3A%2F%2Fbrochures.audiusa.com%2Fbrochures%2Faudi.a7.2012%2Findex.html&amp;rfr_id=info:sid/en.wikipedia.org:Audi_A7"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-6"><span class="mw-cite-backlink"><b><a href="#cite_ref-6">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.autoexpress.co.uk/carreviews/firstdrives/256879/audi_a7_30_tdi.html">"Auto Express September 2010"</a>. Autoexpress.co.uk<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.autoexpress.co.uk/carreviews/firstdrives/256879/audi_a7_30_tdi.html">http://www.autoexpress.co.uk/carreviews/firstdrives/256879/audi_a7_30_tdi.html</a></span><span class="reference-accessdate">. Retrieved 17 June 2011</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=Auto+Express+September+2010&amp;rft.atitle=&amp;rft.pub=Autoexpress.co.uk&amp;rft_id=http%3A%2F%2Fwww.autoexpress.co.uk%2Fcarreviews%2Ffirstdrives%2F256879%2Faudi_a7_30_tdi.html&amp;rfr_id=info:sid/en.wikipedia.org:Audi_A7"><span style="display: none;">&#160;</span></span></span></li>   
URLS;
        $car->setLongDescription($lDesc);
        $car->setShortDescription($sDesc);
        $car->setUrls($urls);
        $car->setVendor($manager->merge($this->getReference('audi_vnd')));
        $manager->persist($car);
        $manager->flush();
    }
    
    public function getOrder() {
        return 65;
    }
}

?>
