<?php

namespace Trig\SimpleShopBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Trig\SimpleShopBundle\Entity\Car;

class CarAstonMartinVanquish extends AbstractFixture implements OrderedFixtureInterface{
    
    public function load(ObjectManager $manager) {
        $car = new Car();
        $car->setName('Aston Martin Vanquish');
        $car->setPrice('300000');
        $car->setImage("/bundles/trigsimpleshop/img/am/minimized/mnmz_aston-martin-vanquish-01.jpg");
        $lDesc = <<< LDESC
   Aston Martin unveiled the Project AM310 Concept at the Concorso D’Eleganza at Villa D'Este on the shores of Lake Como, Italy. The concept showed how the future successor to the DBS would look like.[5] Aston Martin later announced that the concept would be put into production as the all new Aston Martin Vanquish.[6]
The exterior styling of the Vanquish is an evolution of the DBS with many styling cues such as the elongated side strakes being inspired by the One-77. The boot lid includes an integrated rear spoiler which designed to look as if it was impossible to make on the orders of Aston Martin Chief Executive, Dr. Ulrich Bez. The car has an exposed carbon fibre skirt showing its all carbon fibre body. The Vanquish uses the new Generation 4 VH chassis which is lighter and uses more carbon fibre than the Generation 2 VH used in the DBS.[7]
The car features an all new interior based on the one found in the exclusive Aston Martin One-77. The standard interior is trimmed in hand stitched leather and alcantara available in a range of colours. The centre stack features an improved infotainment system over the one found in the DBS.[8] The car is available as either a 2-seater or 2+2.[9]
The Vanquish uses an upgraded version of Aston Martin’s flagship V12 engine with a power output of 573 PS (421 kW; 565 bhp) at 6,750 rpm and torque of 620 N·m (460 lb·ft) at 5,500 rpm. Like most Aston Martins, the engine is front mid mounted with the power going to the rear wheels. It uses a fully catalysed stainless steel exhaust system with active bypass valves. The Vanquish uses an updated touchtronic2 transmission, Aston Martin's automatic gearbox, and unlike the DBS is only available as an automatic. It will be the first Aston Martin available with launch control.[9]
The brakes are ventilated carbon ceramic discs, 398 mm (15.7 in) six-piston callipers in the front and 360 mm (14.2 in) four-piston callipers in the rear. The suspension is a lightweight aluminium front sub frame with hollow castings with independent double wishbone incorporating anti-dive geometry, coil springs, anti-roll bar and monotube adaptive dampers in the front and independent double wishbones with anti-squat and anti-lift geometry, coil springs, anti-roll bar and monotube adaptive dampers in the rear. It has a three stage adjustable adaptive damping system including normal, sport and track modes. The tires are Pirelli P Zeros, 255/ZR20 in the front and 305/30 ZR20 in the rear.[10]
Deliveries are expected to begin in the UK and Europe in late 2012.[11]
LDESC;
        $sDesc = <<< SDESC
   The Aston Martin Vanquish is a grand tourer that was in 2001 as a successor to the ageing Virage range. The original V12 Vanquish, designed by Ian Callum, was unveiled at the 2001 Geneva Motor Show and was produced from 2001 to 2005.It featured as the official James Bond car in the film Die Another Day. The Vanquish S was unveiled in 2004 with a more powerful engine and improved aerodynamics. The Vanquish S and V12 Vanquish were replaced by the DBS in 2007. In 2012 the Vanquish name was revived for the successor to the DBS.
SDESC;
        $urls = <<< URLS
   <li id="cite_note-0"><span class="mw-cite-backlink"><b><a href="#cite_ref-0">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.007.info/FactfileDAD.asp">"James Bond 007 – Die Another Day"</a>. 007.info. 18 November 2002<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.007.info/FactfileDAD.asp">http://www.007.info/FactfileDAD.asp</a></span><span class="reference-accessdate">. Retrieved 20 March 2011</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=James+Bond+007+%E2%80%93+Die+Another+Day&amp;rft.atitle=&amp;rft.date=18+November+2002&amp;rft.pub=007.info&amp;rft_id=http%3A%2F%2Fwww.007.info%2FFactfileDAD.asp&amp;rfr_id=info:sid/en.wikipedia.org:Aston_Martin_Vanquish"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-1"><span class="mw-cite-backlink"><b><a href="#cite_ref-1">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.autotrader.co.uk/EDITORIAL/CARS/news/42009.html">"The Italian Job's Mini Cooper S named best film car"</a>. Autotrader.co.uk. 11 April 2008<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.autotrader.co.uk/EDITORIAL/CARS/news/42009.html">http://www.autotrader.co.uk/EDITORIAL/CARS/news/42009.html</a></span><span class="reference-accessdate">. Retrieved 20 March 2011</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=The+Italian+Job%27s+Mini+Cooper+S+named+best+film+car&amp;rft.atitle=&amp;rft.date=11+April+2008&amp;rft.pub=Autotrader.co.uk&amp;rft_id=http%3A%2F%2Fwww.autotrader.co.uk%2FEDITORIAL%2FCARS%2Fnews%2F42009.html&amp;rfr_id=info:sid/en.wikipedia.org:Aston_Martin_Vanquish"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-2"><span class="mw-cite-backlink"><b><a href="#cite_ref-2">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.automobilemag.com/auto_shows/04gms_bertonejet2/index.html">"Geneva 2004 – Bertone Jet 2 Concept – Automobile Magazine"</a>. Automobilemag.com. 13 December 2010<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.automobilemag.com/auto_shows/04gms_bertonejet2/index.html">http://www.automobilemag.com/auto_shows/04gms_bertonejet2/index.html</a></span><span class="reference-accessdate">. Retrieved 20 March 2011</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=Geneva+2004+%E2%80%93+Bertone+Jet+2+Concept++%E2%80%93+Automobile+Magazine&amp;rft.atitle=&amp;rft.date=13+December+2010&amp;rft.pub=Automobilemag.com&amp;rft_id=http%3A%2F%2Fwww.automobilemag.com%2Fauto_shows%2F04gms_bertonejet2%2Findex.html&amp;rfr_id=info:sid/en.wikipedia.org:Aston_Martin_Vanquish"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-3"><span class="mw-cite-backlink"><b><a href="#cite_ref-3">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://autoweek.com/apps/pbcs.dll/article?AID=/20040517/FREE/405170711&amp;SearchID=7328298156718">"2005 Aston Martin Zagato Vanquish Roadster – AutoWeek Magazine"</a>. Autoweek.com. 17 May 2004<span class="printonly">. <a rel="nofollow" class="external free" href="http://autoweek.com/apps/pbcs.dll/article?AID=/20040517/FREE/405170711&amp;SearchID=7328298156718">http://autoweek.com/apps/pbcs.dll/article?AID=/20040517/FREE/405170711&amp;SearchID=7328298156718</a></span><span class="reference-accessdate">. Retrieved 20 March 2011</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=2005+Aston+Martin+Zagato+Vanquish+Roadster+%E2%80%93+AutoWeek+Magazine&amp;rft.atitle=&amp;rft.date=17+May+2004&amp;rft.pub=Autoweek.com&amp;rft_id=http%3A%2F%2Fautoweek.com%2Fapps%2Fpbcs.dll%2Farticle%3FAID%3D%2F20040517%2FFREE%2F405170711%26SearchID%3D7328298156718&amp;rfr_id=info:sid/en.wikipedia.org:Aston_Martin_Vanquish"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-4"><span class="mw-cite-backlink"><b><a href="#cite_ref-4">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.astonmartin.com/en/am310/enquire">"Project AM310 Concept"</a><span class="printonly">. <a rel="nofollow" class="external free" href="http://www.astonmartin.com/en/am310/enquire">http://www.astonmartin.com/en/am310/enquire</a></span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=Project+AM310+Concept&amp;rft.atitle=&amp;rft_id=http%3A%2F%2Fwww.astonmartin.com%2Fen%2Fam310%2Fenquire&amp;rfr_id=info:sid/en.wikipedia.org:Aston_Martin_Vanquish"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-5"><span class="mw-cite-backlink"><b><a href="#cite_ref-5">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.astonmartin.com/cars/vanquish">"Aston Martin Vanquish"</a><span class="printonly">. <a rel="nofollow" class="external free" href="http://www.astonmartin.com/cars/vanquish">http://www.astonmartin.com/cars/vanquish</a></span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=Aston+Martin+Vanquish&amp;rft.atitle=&amp;rft_id=http%3A%2F%2Fwww.astonmartin.com%2Fcars%2Fvanquish&amp;rfr_id=info:sid/en.wikipedia.org:Aston_Martin_Vanquish"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-6"><span class="mw-cite-backlink"><b><a href="#cite_ref-6">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.astonmartin.com/en/cars/vanquish/exterior">"Aston Martin Vanquish Exterior"</a><span class="printonly">. <a rel="nofollow" class="external free" href="http://www.astonmartin.com/en/cars/vanquish/exterior">http://www.astonmartin.com/en/cars/vanquish/exterior</a></span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=Aston+Martin+Vanquish+Exterior&amp;rft.atitle=&amp;rft_id=http%3A%2F%2Fwww.astonmartin.com%2Fen%2Fcars%2Fvanquish%2Fexterior&amp;rfr_id=info:sid/en.wikipedia.org:Aston_Martin_Vanquish"><span style="display: none;">&#160;</span></span></span></li>
URLS;
        $car->setLongDescription($lDesc);
        $car->setShortDescription($sDesc);
        $car->setUrls($urls);
        $car->setVendor($manager->merge($this->getReference('am_vnd')));
        $manager->persist($car);
        $manager->flush();
    }
    
    public function getOrder() {
        return 60;
    }
}

?>
