<?php

namespace Trig\SimpleShopBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Trig\SimpleShopBundle\Entity\Car;

class CarAstonMartinVantage2005 extends AbstractFixture implements OrderedFixtureInterface{
    
    public function load(ObjectManager $manager) {
        $car = new Car();
        $car->setName('Aston Martin Vantage (2005)');
        $car->setPrice('220000');
        $car->setImage("/bundles/trigsimpleshop/img/am/minimized/mnmz_aston-martin-dbs-v123.jpg");
        $lDesc = <<< LDESC
   Following the unveiling of the AMV8 Vantage concept car in 2003, the production V8 Vantage was introduced at the Geneva Motor Show in 2005 for the 2006 model year. The two seat, two -door coupe had a bonded aluminium structure for strength and lightness. The 172.5 inch (4.38 m) long coupe featured a hatchback-style tailgate for practicality, with a large luggage shelf behind the seats. In addition to the coupe, a convertible, known as the V8 Vantage Roadster, is available .[1]
The V8 Vantage was initially powered by a 4.3 L (4300 cc) quad-cam 32-valve V8 which produced 380 hp (280 kW) at 7,300 rpm and 302 lb·ft (409 N·m) at 5,000 rpm. However models produced after 2008 had a 4.7 litre 420 hp (313 kW) V8.[2] Though based loosely on Jaguar's AJ-V8 engine architecture, this engine was unique to Aston Martin and featured race-style dry-sump lubrication, which enabled it to be mounted low in the chassis for an improved center of gravity. The cylinder block and heads, crankshaft, connecting rods, pistons, camshafts, inlet and exhaust manifolds, lubrication system, and engine management were all Aston Martin designs and the V8 engine was assembled by hand at the AM facility in Cologne, Germany, which also built the V12 engine for the DB9 and Vanquish.
The engine was front mid-mounted with a rear-mounted transaxle, giving a 49/51 front/rear weight distribution. Slotted Brembo brakes were also standard. The original V8 Vantage could accelerate to 60 mph (97 km/h) in 4.7 seconds topping out at 175 mph (282 km/h).[3] Vantages with the enhanced 400 HP version of the 4.3 L V8 engine (included with the "N400" package or available individually as a Power Upgrade kit) as well as later models with the 4.7 L V8 and 6.0 L V12 were even faster.
In 2008 Aston introduced an aftermarket dealer approved upgrade path for power and handling of the 4.3L variants that maintained the warranty with Aston. The power upgrade was The V8 Vantage Power Upgrade, creating a more potent version of the Aston Martin 4.3 litre engine with an increase in Peak power of 20 bhp to 400 bhp while peak torque is increased by 10Nm to 420Nm. This consists of the fitting of the following revised components; manifold assembly (painted Crackle Black), valved air box, right and left hand side vacuum hose assemblies, engine bay fuse box link lead (ECU to fuse box), throttle body to manifold gasket, intake manifold gasket, fuel injector to manifold seal, and a manifold badge.
The V8 Vantage retailed for ?79,000, US$110,000, or €104,000 in 2006,[2] Aston Martin planned to build up to 3,000 per year. Included was a six-speed manual transmission and leather-upholstery for the seats, dash, steering-wheel, and shift-knob. A six-speed sequential manual transmission, similar to those produced by Ferrari and Lamborghini, called Sportshift was introduced later as an option.
In their 2006 readership survey, readers of Car Design News voted the Aston Martin V8 Vantage as the best current production car design. The survey results were based on over 1000 responses, most from working automotive designers and students of industrial and automotive design. The Vantage was also voted one of Automobile magazine's 2007 "All Stars" for its performance, road manners, and design. The V8 Vantage is also one of the only two cars to be added to "The DB9 section," – a fridge reserved for the super-"cool" – on the BBC's Top Gear (on which it is described as the baby Aston to differentiate it from the V12 powered DB9). The program rates cars from seriously un-cool to sub-zero. The fridge was an extra category added when the presenters deemed the Aston Martin DB9 too cool for the sub-zero category. In the 2005 awards, Jeremy Clarkson declared the V8 Vantage as Best Sounding Car of the Year and The Coolest Car of the Year, while the award winner was actually the Porsche 911. While the V8 Vantage remains a rare and special car by any standard, the success of the model is highlighted by the completion of chassis number 10,000 – a specially ordered Onyx Coupe delivered to a customer in USA – in the first half of 2008. While the production of 10,000 cars is a tiny number by the standards of typical car manufacturers, it is a significant milestone for an Aston Martin model – the DB9 being the only other Aston Martin model to have achieved that figure.
LDESC;
        $sDesc = <<< SDESC
 The Aston Martin V8 Vantage and the Aston Martin V12 Vantage are a series of hand-built sports cars from the British manufacturer Aston Martin. Aston Martin has previously used the "Vantage" name on high-performance variants of their existing GT models, notably on the Virage-based car of the 1990s. The modern car, in contrast, is the leanest and most agile car in Aston's lineup. As such, it is intended as a more focused model to reach out to potential buyers of cars such as the Porsche 911 as well as the exotic sports and GT cars with which Aston Martins traditionally compete.  
SDESC;
        $urls = <<< URLS
  <li id="cite_note-amoc.org-0"><span class="mw-cite-backlink"><b><a href="#cite_ref-amoc.org_0-0">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.amoc.org/index.php?option=com_content&amp;task=view&amp;id=603&amp;Itemid=186">"Aston Martin Owners Club"</a>. Amoc.org<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.amoc.org/index.php?option=com_content&amp;task=view&amp;id=603&amp;Itemid=186">http://www.amoc.org/index.php?option=com_content&amp;task=view&amp;id=603&amp;Itemid=186</a></span><span class="reference-accessdate">. Retrieved 20 March 2010</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=Aston+Martin+Owners+Club&amp;rft.atitle=&amp;rft.pub=Amoc.org&amp;rft_id=http%3A%2F%2Fwww.amoc.org%2Findex.php%3Foption%3Dcom_content%26task%3Dview%26id%3D603%26Itemid%3D186&amp;rfr_id=info:sid/en.wikipedia.org:Aston_Martin_Vantage_(2005)"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-autos.msn.com-1"><span class="mw-cite-backlink">^ <a href="#cite_ref-autos.msn.com_1-0"><sup><i><b>a</b></i></sup></a> <a href="#cite_ref-autos.msn.com_1-1"><sup><i><b>b</b></i></sup></a></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://autos.msn.com/research/vip/Spec_Glance.aspx?year=2006&amp;make=Aston%20Martin&amp;model=V8%20Vantage&amp;trimid=-1">"2006 Aston Martin V8 Vantage Specs and Features – MSN Autos"</a>. Autos.msn.com. 22 February 2010<span class="printonly">. <a rel="nofollow" class="external free" href="http://autos.msn.com/research/vip/Spec_Glance.aspx?year=2006&amp;make=Aston%20Martin&amp;model=V8%20Vantage&amp;trimid=-1">http://autos.msn.com/research/vip/Spec_Glance.aspx?year=2006&amp;make=Aston%20Martin&amp;model=V8%20Vantage&amp;trimid=-1</a></span><span class="reference-accessdate">. Retrieved 20 March 2010</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=2006+Aston+Martin+V8+Vantage+Specs+and+Features+%E2%80%93+MSN+Autos&amp;rft.atitle=&amp;rft.date=22+February+2010&amp;rft.pub=Autos.msn.com&amp;rft_id=http%3A%2F%2Fautos.msn.com%2Fresearch%2Fvip%2FSpec_Glance.aspx%3Fyear%3D2006%26make%3DAston%2520Martin%26model%3DV8%2520Vantage%26trimid%3D-1&amp;rfr_id=info:sid/en.wikipedia.org:Aston_Martin_Vantage_(2005)"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-2"><span class="mw-cite-backlink"><b><a href="#cite_ref-2">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.roadandtrack.com/tests/car/2006-aston-martin-v8-vantage">"Aston Martin V8 Vantage"</a>. Road and Track Magazine<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.roadandtrack.com/tests/car/2006-aston-martin-v8-vantage">http://www.roadandtrack.com/tests/car/2006-aston-martin-v8-vantage</a></span><span class="reference-accessdate">. Retrieved 15 June 2010</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=Aston+Martin+V8+Vantage&amp;rft.atitle=&amp;rft.pub=Road+and+Track+Magazine&amp;rft_id=http%3A%2F%2Fwww.roadandtrack.com%2Ftests%2Fcar%2F2006-aston-martin-v8-vantage&amp;rfr_id=info:sid/en.wikipedia.org:Aston_Martin_Vantage_(2005)"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-3"><span class="mw-cite-backlink"><b><a href="#cite_ref-3">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.automoblog.net/2008/12/23/2009-aston-martin-v8-vantage-review/">"2009 Aston Martin V8 Vantage Review"</a>. Automoblog.net. 23 December 2008<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.automoblog.net/2008/12/23/2009-aston-martin-v8-vantage-review/">http://www.automoblog.net/2008/12/23/2009-aston-martin-v8-vantage-review/</a></span><span class="reference-accessdate">. Retrieved 30 September 2010</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=2009+Aston+Martin+V8+Vantage+Review&amp;rft.atitle=&amp;rft.date=23+December+2008&amp;rft.pub=Automoblog.net&amp;rft_id=http%3A%2F%2Fwww.automoblog.net%2F2008%2F12%2F23%2F2009-aston-martin-v8-vantage-review%2F&amp;rfr_id=info:sid/en.wikipedia.org:Aston_Martin_Vantage_(2005)"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-4"><span class="mw-cite-backlink"><b><a href="#cite_ref-4">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.astonmartin.com/eng/thecompany/news?a=71f4deb1-9e51-4f5c-a6ea-9665fa6cc37c">"Technical Enhancements for Aston Martin V8 Vantage"</a>. Astonmartin.com. 23 May 2008<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.astonmartin.com/eng/thecompany/news?a=71f4deb1-9e51-4f5c-a6ea-9665fa6cc37c">http://www.astonmartin.com/eng/thecompany/news?a=71f4deb1-9e51-4f5c-a6ea-9665fa6cc37c</a></span><span class="reference-accessdate">. Retrieved 30 September 2010</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=Technical+Enhancements+for+Aston+Martin+V8+Vantage&amp;rft.atitle=&amp;rft.date=23+May+2008&amp;rft.pub=Astonmartin.com&amp;rft_id=http%3A%2F%2Fwww.astonmartin.com%2Feng%2Fthecompany%2Fnews%3Fa%3D71f4deb1-9e51-4f5c-a6ea-9665fa6cc37c&amp;rfr_id=info:sid/en.wikipedia.org:Aston_Martin_Vantage_(2005)"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-5"><span class="mw-cite-backlink"><b><a href="#cite_ref-5">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.caranddriver.com/reviews/hot_lists/high_performance/sports_car_central/2008_aston_martin_v_8_vantage_roadster_first_drive_review">"Car and Driver review of V8 Vantage Roadster"</a>. Caranddriver.com<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.caranddriver.com/reviews/hot_lists/high_performance/sports_car_central/2008_aston_martin_v_8_vantage_roadster_first_drive_review">http://www.caranddriver.com/reviews/hot_lists/high_performance/sports_car_central/2008_aston_martin_v_8_vantage_roadster_first_drive_review</a></span><span class="reference-accessdate">. Retrieved 30 September 2010</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=Car+and+Driver+review+of+V8+Vantage+Roadster&amp;rft.atitle=&amp;rft.pub=Caranddriver.com&amp;rft_id=http%3A%2F%2Fwww.caranddriver.com%2Freviews%2Fhot_lists%2Fhigh_performance%2Fsports_car_central%2F2008_aston_martin_v_8_vantage_roadster_first_drive_review&amp;rfr_id=info:sid/en.wikipedia.org:Aston_Martin_Vantage_(2005)"><span style="display: none;">&#160;</span></span></span></li> 
URLS;
        $car->setLongDescription($lDesc);
        $car->setShortDescription($sDesc);
        $car->setUrls($urls);
        $car->setVendor($manager->merge($this->getReference('am_vnd')));
        $manager->persist($car);
        $manager->flush();
    }
    
    public function getOrder() {
        return 59;
    }
}

?>
