<?php

namespace Trig\SimpleShopBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Trig\SimpleShopBundle\Entity\Car;

class CarAudiA5Coupe extends AbstractFixture implements OrderedFixtureInterface{
    
    public function load(ObjectManager $manager) {
        $car = new Car();
        $car->setName('Audi A5 Coupe');
        $car->setPrice('120000');
        $car->setImage("/bundles/trigsimpleshop/img/audi/minimized/mnmz_a5.jpg");
        $lDesc = <<< LDESC
   The design was based on Nuvolari quattro concept car. Audi A5 and S5 Coupe models were unveiled simultaneously in Salon International de l'Auto (Geneva) and Melbourne International Motor Shows on March 6, 2007.
Ordering of the A5 and S5 began on June 6, 2007 and the first delivery was made 11 months later. Launch models included 3.2 FSI V6 multitronic and 3.0 TDI quattro 6-speed, with 1.8 TFSI available in autumn 2007.
Early US models included the A5 3.2 FSI quattro and the S5 coupe 4.2 FSI quattro. Both vehicles included choice of a 6-speed manual or 6-speed Tiptronic automatic transmission. The S5 model went on sale in November 2007, equipped only with a manual transmission, while the A5 and the Tiptronic went on sale beginning spring of 2008.
Canadian models went on sale in 2008. Launch model included A5 3.2 FSI with choice of 6-speed manual or 6-speed Tiptronic transmission. Current models (.i.e. 2011 are only available with the 2.0 L Turbo engines, the 3.2 L is no longer available for the A5 in Canada.
LDESC;
        $sDesc = <<< SDESC
   The Audi A5 (internally designated Typ 8T) is a coupe produced by the German automobile manufacturer Audi since 2007. It is the coupe, cabriolet, and five-door fastback versions of the fourth generation (B8) Audi A4 saloon and estate models.
SDESC;
        $urls = <<< URLS
   <li id="cite_note-specs-0"><span class="mw-cite-backlink">^ <a href="#cite_ref-specs_0-0"><sup><i><b>a</b></i></sup></a> <a href="#cite_ref-specs_0-1"><sup><i><b>b</b></i></sup></a></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.jbcarpages.com/audi/a5/2008/specs/">"2008 Audi A5 and S5 Specs"</a>. JB car pages<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.jbcarpages.com/audi/a5/2008/specs/">http://www.jbcarpages.com/audi/a5/2008/specs/</a></span><span class="reference-accessdate">. Retrieved 2008-10-28</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=2008+Audi+A5+and+S5+Specs&amp;rft.atitle=&amp;rft.pub=JB+car+pages&amp;rft_id=http%3A%2F%2Fwww.jbcarpages.com%2Faudi%2Fa5%2F2008%2Fspecs%2F&amp;rfr_id=info:sid/en.wikipedia.org:Audi_A5"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-1"><span class="mw-cite-backlink"><b><a href="#cite_ref-1">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.audiworld.com/news/07/audi-a5-geneva-first-impression/">"First Look: Audi A5 and S5 Debut at Geneva"</a>. Audiworld.com<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.audiworld.com/news/07/audi-a5-geneva-first-impression/">http://www.audiworld.com/news/07/audi-a5-geneva-first-impression/</a></span><span class="reference-accessdate">. Retrieved 2010-10-20</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=First+Look%3A+Audi+A5+and+S5+Debut+at+Geneva&amp;rft.atitle=&amp;rft.pub=Audiworld.com&amp;rft_id=http%3A%2F%2Fwww.audiworld.com%2Fnews%2F07%2Faudi-a5-geneva-first-impression%2F&amp;rfr_id=info:sid/en.wikipedia.org:Audi_A5"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-2"><span class="mw-cite-backlink"><b><a href="#cite_ref-2">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.audiworld.com/news/07/audi-a5-s5/">"Elegance and Dynamism: The New Audi A5 / Audi S5"</a>. Audiworld.com. <a rel="nofollow" class="external text" href="http://web.archive.org/web/20101006050941/http://www.audiworld.com/news/07/audi-a5-s5/">Archived</a> from the original on 6 October 2010<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.audiworld.com/news/07/audi-a5-s5/">http://www.audiworld.com/news/07/audi-a5-s5/</a></span><span class="reference-accessdate">. Retrieved 2010-10-20</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=Elegance+and+Dynamism%3A+The+New+Audi+A5+%2F+Audi+S5&amp;rft.atitle=&amp;rft.pub=Audiworld.com&amp;rft_id=http%3A%2F%2Fwww.audiworld.com%2Fnews%2F07%2Faudi-a5-s5%2F&amp;rfr_id=info:sid/en.wikipedia.org:Audi_A5"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-3"><span class="mw-cite-backlink"><b><a href="#cite_ref-3">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.audiworld.com/news/07/a5-s5-in-depth/at-a-glance/content.shtml">"The Audi A5: At-a-Glance"</a>. Audiworld.com. 2007-04-16<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.audiworld.com/news/07/a5-s5-in-depth/at-a-glance/content.shtml">http://www.audiworld.com/news/07/a5-s5-in-depth/at-a-glance/content.shtml</a></span><span class="reference-accessdate">. Retrieved 2010-10-20</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=The+Audi+A5%3A+At-a-Glance&amp;rft.atitle=&amp;rft.date=2007-04-16&amp;rft.pub=Audiworld.com&amp;rft_id=http%3A%2F%2Fwww.audiworld.com%2Fnews%2F07%2Fa5-s5-in-depth%2Fat-a-glance%2Fcontent.shtml&amp;rfr_id=info:sid/en.wikipedia.org:Audi_A5"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-4"><span class="mw-cite-backlink"><b><a href="#cite_ref-4">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.audiworld.com/news/07/a5-s5-us-pricing/content.shtml">"Audi Announces U.S. Pricing for 2008 A5 and S5 Models"</a>. Audiworld.com. 2007-09-05<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.audiworld.com/news/07/a5-s5-us-pricing/content.shtml">http://www.audiworld.com/news/07/a5-s5-us-pricing/content.shtml</a></span><span class="reference-accessdate">. Retrieved 2010-10-20</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=Audi+Announces+U.S.+Pricing+for+2008+A5+and+S5+Models&amp;rft.atitle=&amp;rft.date=2007-09-05&amp;rft.pub=Audiworld.com&amp;rft_id=http%3A%2F%2Fwww.audiworld.com%2Fnews%2F07%2Fa5-s5-us-pricing%2Fcontent.shtml&amp;rfr_id=info:sid/en.wikipedia.org:Audi_A5"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-5"><span class="mw-cite-backlink"><b><a href="#cite_ref-5">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.audiworld.com/news/08/canadian-a5-pricing/content.shtml">"Audi Canada Announces Pricing for All-New A5 Coupe"</a>. Audiworld.com. 2008-01-22. <a rel="nofollow" class="external text" href="http://web.archive.org/web/20101014184417/http://www.audiworld.com/news/08/canadian-a5-pricing/content.shtml">Archived</a> from the original on 14 October 2010<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.audiworld.com/news/08/canadian-a5-pricing/content.shtml">http://www.audiworld.com/news/08/canadian-a5-pricing/content.shtml</a></span><span class="reference-accessdate">. Retrieved 2010-10-20</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=Audi+Canada+Announces+Pricing+for+All-New+A5+Coupe&amp;rft.atitle=&amp;rft.date=2008-01-22&amp;rft.pub=Audiworld.com&amp;rft_id=http%3A%2F%2Fwww.audiworld.com%2Fnews%2F08%2Fcanadian-a5-pricing%2Fcontent.shtml&amp;rfr_id=info:sid/en.wikipedia.org:Audi_A5"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-6"><span class="mw-cite-backlink"><b><a href="#cite_ref-6">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.audiworld.com/news/08/a5-s5-cabriolet/content.shtml">"The Audi A5 / S5 Cabriolet - the Joy of Open-Top Driving"</a>. Audiworld.com. 2008-12-02<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.audiworld.com/news/08/a5-s5-cabriolet/content.shtml">http://www.audiworld.com/news/08/a5-s5-cabriolet/content.shtml</a></span><span class="reference-accessdate">. Retrieved 2010-10-20</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=The+Audi+A5+%2F+S5+Cabriolet+-+the+Joy+of+Open-Top+Driving&amp;rft.atitle=&amp;rft.date=2008-12-02&amp;rft.pub=Audiworld.com&amp;rft_id=http%3A%2F%2Fwww.audiworld.com%2Fnews%2F08%2Fa5-s5-cabriolet%2Fcontent.shtml&amp;rfr_id=info:sid/en.wikipedia.org:Audi_A5"><span style="display: none;">&#160;</span></span></span></li>
URLS;
        $car->setLongDescription($lDesc);
        $car->setShortDescription($sDesc);
        $car->setUrls($urls);
        $car->setVendor($manager->merge($this->getReference('audi_vnd')));
        $manager->persist($car);
        $manager->flush();
    }
    
    public function getOrder() {
        return 57;
    }
}

?>
