<?php

namespace Trig\SimpleShopBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Trig\SimpleShopBundle\Entity\Car;

class CarBMWX5 extends AbstractFixture implements OrderedFixtureInterface{
    
    public function load(ObjectManager $manager) {
        $car = new Car();
        $car->setName('BMW X5');
        $car->setPrice('55000');
        $car->setImage("/bundles/trigsimpleshop/img/bmw/minimized/mnmz_x5_full.jpg");
        $lDesc = <<< LDESC
   The xDrive AWD system updates previewed in the facelifted X5 have continued with further detail improvements for the E70. It uses a double wishbone suspension at the front. The manual transmission is entirely dropped, leaving only the automatic transmission.
The E70 features many new technological advancements for this class as standard equipment including BMW's iDrive system, electronic 'joystick' gearshift (no mechanical connection to the gearbox to win space in the console), LED taillamps, the first ever all-polypropylene single module fender module, and options such as head-up display HUD, active steering, active damping, and Dynamic Drive which uses active anti-roll bars which use a hydraulic servo in the middle to actively counteract body roll.
The interior of the new, larger, X5 is completely new. It has a large center-mounted display screen and the simplified iDrive, a man-machine interface system also found in the rest of the BMW model range. The E70 further incorporates many comfort options such as a glass panorama-roof, and, for the first time in a BMW, an optional third row seat which has increased the seating capacity in E70 to 7 passengers, addressing criticism of the E53 model which had been regarded as being slightly too small for this market segment.
The E70 is also the first production vehicle to use FlexRay, a new extremely fast electrical bus system; it is only used for the control of the chassis damping system. The new 'joy-stick'-style electronic space-saving shifter has since been adopted in the new 2008 BMW 5 Series.
For the 2010 model year the X5 received the new iDrive system and the BMW individual audio system along with various other minor updates.
LDESC;
        $sDesc = <<< SDESC
   The BMW X5 is a midsize luxury CUV (Crossover Utility Vehicle) (J-segment in Europe) produced by BMW. The first generation of the X5, with the chassis code E53, made its debut in 1999. It was BMW's first SUV (Sport Utility Vehicle), also known as "Four-by-Four" (4x4) in the UK, which featured 4WD all-wheel drive and was available with either manual or automatic transmission. In 2006 the second generation X5 was launched, known internally as the E70, featuring the torque-split capable xDrive all-wheel drive system mated to an automatic transmission, and in 2009 the X5 M performance variant was released as a 2010 model.
SDESC;
        $urls = <<< URLS
   <li id="cite_note-0"><span class="mw-cite-backlink"><b><a href="#cite_ref-0">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.avtotor.ru/index.php?option=com_content&amp;view=article&amp;id=117&amp;Itemid=486">"Группа компаний Автотор&#160;:: Автомобили BMW"</a>. Avtotor.ru<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.avtotor.ru/index.php?option=com_content&amp;view=article&amp;id=117&amp;Itemid=486">http://www.avtotor.ru/index.php?option=com_content&amp;view=article&amp;id=117&amp;Itemid=486</a></span><span class="reference-accessdate">. Retrieved 2010-11-04</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=%D0%93%D1%80%D1%83%D0%BF%D0%BF%D0%B0+%D0%BA%D0%BE%D0%BC%D0%BF%D0%B0%D0%BD%D0%B8%D0%B9+%D0%90%D0%B2%D1%82%D0%BE%D1%82%D0%BE%D1%80+%3A%3A+%D0%90%D0%B2%D1%82%D0%BE%D0%BC%D0%BE%D0%B1%D0%B8%D0%BB%D0%B8+BMW&amp;rft.atitle=&amp;rft.pub=Avtotor.ru&amp;rft_id=http%3A%2F%2Fwww.avtotor.ru%2Findex.php%3Foption%3Dcom_content%26view%3Darticle%26id%3D117%26Itemid%3D486&amp;rfr_id=info:sid/en.wikipedia.org:BMW_X5_(E70)"><span style="display: none;">&#160;</span></span> <span class="languageicon" style="font-size:0.95em; font-weight:bold; color:#555;">(Russian)</span></span></li>
<li id="cite_note-x5athens-1"><span class="mw-cite-backlink">^ <a href="#cite_ref-x5athens_1-0"><sup><i><b>a</b></i></sup></a> <a href="#cite_ref-x5athens_1-1"><sup><i><b>b</b></i></sup></a></span> <span class="reference-text"><span class="citation web">Tan, Paul. <a rel="nofollow" class="external text" href="http://paultan.org/archives/2006/11/21/2007-bmw-x5-48i-and-30d-test-drive-in-athens/">"2007 BMW X5 4.8i Test Drive in Athens"</a>. Paultan.org<span class="printonly">. <a rel="nofollow" class="external free" href="http://paultan.org/archives/2006/11/21/2007-bmw-x5-48i-and-30d-test-drive-in-athens/">http://paultan.org/archives/2006/11/21/2007-bmw-x5-48i-and-30d-test-drive-in-athens/</a></span><span class="reference-accessdate">. Retrieved 2010-10-03</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=2007+BMW+X5+4.8i+Test+Drive+in+Athens&amp;rft.atitle=&amp;rft.aulast=Tan&amp;rft.aufirst=Paul&amp;rft.au=Tan%2C%26%2332%3BPaul&amp;rft.pub=Paultan.org&amp;rft_id=http%3A%2F%2Fpaultan.org%2Farchives%2F2006%2F11%2F21%2F2007-bmw-x5-48i-and-30d-test-drive-in-athens%2F&amp;rfr_id=info:sid/en.wikipedia.org:BMW_X5_(E70)"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-2"><span class="mw-cite-backlink"><b><a href="#cite_ref-2">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.borealisgroup.com/industry-solutions/mobility/125340/">"Polypropylene provides an economic aid to automotive industry recovery and advance"</a>. Borealisgroup.com<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.borealisgroup.com/industry-solutions/mobility/125340/">http://www.borealisgroup.com/industry-solutions/mobility/125340/</a></span><span class="reference-accessdate">. Retrieved 2010-10-03</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=Polypropylene+provides+an+economic+aid+to+automotive+industry+recovery+and+advance&amp;rft.atitle=&amp;rft.pub=Borealisgroup.com&amp;rft_id=http%3A%2F%2Fwww.borealisgroup.com%2Findustry-solutions%2Fmobility%2F125340%2F&amp;rfr_id=info:sid/en.wikipedia.org:BMW_X5_(E70)"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-3"><span class="mw-cite-backlink"><b><a href="#cite_ref-3">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.caranddriver.com/reviews/comparisons/09q4/x5_m_vs._grand_cherokee_srt8_range_rover_sport_supercharged_cayenne_turbo_s_-comparison_tests">"X5 M vs. Grand Cherokee SRT8, Range Rover Sport Supercharged, Cayenne Turbo S"</a>. Car and Driver<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.caranddriver.com/reviews/comparisons/09q4/x5_m_vs._grand_cherokee_srt8_range_rover_sport_supercharged_cayenne_turbo_s_-comparison_tests">http://www.caranddriver.com/reviews/comparisons/09q4/x5_m_vs._grand_cherokee_srt8_range_rover_sport_supercharged_cayenne_turbo_s_-comparison_tests</a></span><span class="reference-accessdate">. Retrieved 2011-08-10</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=X5+M+vs.+Grand+Cherokee+SRT8%2C+Range+Rover+Sport+Supercharged%2C+Cayenne+Turbo+S&amp;rft.atitle=&amp;rft.pub=Car+and+Driver&amp;rft_id=http%3A%2F%2Fwww.caranddriver.com%2Freviews%2Fcomparisons%2F09q4%2Fx5_m_vs._grand_cherokee_srt8_range_rover_sport_supercharged_cayenne_turbo_s_-comparison_tests&amp;rfr_id=info:sid/en.wikipedia.org:BMW_X5_(E70)"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-bmwusa.com-4"><span class="mw-cite-backlink">^ <a href="#cite_ref-bmwusa.com_4-0"><sup><i><b>a</b></i></sup></a> <a href="#cite_ref-bmwusa.com_4-1"><sup><i><b>b</b></i></sup></a></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.bmwusa.com/Standard/Content/Vehicles/2011/X5/xDrive35i/Features_and_Specs/X5xDrive35iSpecifications.aspx">"BMW X5 xDrive35i - Model Overview - BMW North America"</a>. Bmwusa.com<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.bmwusa.com/Standard/Content/Vehicles/2011/X5/xDrive35i/Features_and_Specs/X5xDrive35iSpecifications.aspx">http://www.bmwusa.com/Standard/Content/Vehicles/2011/X5/xDrive35i/Features_and_Specs/X5xDrive35iSpecifications.aspx</a></span><span class="reference-accessdate">. Retrieved 2011-08-10</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=BMW+X5+xDrive35i+-+Model+Overview+-+BMW+North+America&amp;rft.atitle=&amp;rft.pub=Bmwusa.com&amp;rft_id=http%3A%2F%2Fwww.bmwusa.com%2FStandard%2FContent%2FVehicles%2F2011%2FX5%2FxDrive35i%2FFeatures_and_Specs%2FX5xDrive35iSpecifications.aspx&amp;rfr_id=info:sid/en.wikipedia.org:BMW_X5_(E70)"><span style="display: none;">&#160;</span></span></span></li>
<li id="cite_note-5"><span class="mw-cite-backlink"><b><a href="#cite_ref-5">^</a></b></span> <span class="reference-text"><span class="citation web"><a rel="nofollow" class="external text" href="http://www.autoblog.com/2010/02/06/officially-official-2011-bmw-x5-goes-all-turbo/">"Officially Official: 2011 BMW X5 goes all turbo"</a>. autoblog.com. 2010-02-09<span class="printonly">. <a rel="nofollow" class="external free" href="http://www.autoblog.com/2010/02/06/officially-official-2011-bmw-x5-goes-all-turbo/">http://www.autoblog.com/2010/02/06/officially-official-2011-bmw-x5-goes-all-turbo/</a></span><span class="reference-accessdate">. Retrieved 2010-02-09</span>.</span><span class="Z3988" title="ctx_ver=Z39.88-2004&amp;rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Abook&amp;rft.genre=bookitem&amp;rft.btitle=Officially+Official%3A+2011+BMW+X5+goes+all+turbo&amp;rft.atitle=&amp;rft.date=2010-02-09&amp;rft.pub=autoblog.com&amp;rft_id=http%3A%2F%2Fwww.autoblog.com%2F2010%2F02%2F06%2Fofficially-official-2011-bmw-x5-goes-all-turbo%2F&amp;rfr_id=info:sid/en.wikipedia.org:BMW_X5_(E70)"><span style="display: none;">&#160;</span></span></span></li>
URLS;
        $car->setLongDescription($lDesc);
        $car->setShortDescription($sDesc);
        $car->setUrls($urls);
        $car->setVendor($manager->merge($this->getReference('bmw_vnd')));
        $manager->persist($car);
        $manager->flush();
    }
    
    public function getOrder() {
        return 68;
    }
}

?>
