<?php

namespace Trig\SimpleShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends EntityRepository
{
    public function findCarsByVendorName($vName){
        return $this->getEntityManager()
                ->createQuery('select c from Trig\SimpleShopBundle\Entity\Car c join c.vendor v where v.name = :vName')
                ->setParameter('vName', $vName)
                ->getResult();
    }
    
}
