parameters:
    database_driver:   pdo_mysql
    database_host:     db10.freehost.com.ua
    database_port:     ~
    database_name:     petrovchanka_dev
    database_user:     petrovchanka_dev
    database_password: lQx7pOOAe

    mailer_transport:  smtp
    mailer_host:       ubuntu.dev
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
