parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     simpleshop
    database_user:     root
    database_password: vb45nm67

    mailer_transport:  smtp
    mailer_host:       ubuntu.dev
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
